
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s
 */
public class CreateAccount extends javax.swing.JFrame {
    int posX,posY;
    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREATE ACCOUNT");
        setBackground(new java.awt.Color(0, 102, 204));
        setMinimumSize(new java.awt.Dimension(947, 741));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jFrameMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jFrameMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("LAST NAME :");

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("AGE  :");

        jLabel3.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("FIRST NAME :");

        jLabel6.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("USERNAME :");

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("PASSWORD :");

        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("QUALIFICATION :");

        t5.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(204, 204, 204));
        t5.setText("Qualification");
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t5MouseClicked(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t5KeyTyped(evt);
            }
        });

        t6.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t6.setForeground(new java.awt.Color(204, 204, 204));
        t6.setText("Username");
        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t6MouseClicked(evt);
            }
        });
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t6KeyTyped(evt);
            }
        });

        t4.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(204, 204, 204));
        t4.setText("Gender");
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poor Richard", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("GENDER:");

        t3.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(204, 204, 204));
        t3.setText("Age");
        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });

        t2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(204, 204, 204));
        t2.setText("Lastname");
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });

        t1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(204, 204, 204));
        t1.setText("Firstname");
        t1.setToolTipText("Enter First Name");
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });

        t7.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        t7.setForeground(new java.awt.Color(204, 204, 204));
        t7.setText("Password");
        t7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t7MouseClicked(evt);
            }
        });
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t7KeyTyped(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CREATE ACCOUNT");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10Exit(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("Already Registered? Click Here");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel11))
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(356, 0, 593, 741);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE ACCOUNT");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\s\\Downloads\\0_createacc-removebg-preview.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 356, 741);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int a;
        String r="",n="",g="",ql="",u="",p="";
        try{
            r = t1.getText();
            n = t2.getText();
            g = t4.getText();
            ql = t5.getText();
            u = t6.getText();
            p = t7.getText();
            a = Integer.parseInt(t3.getText());
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/imgAuth","root","password");
            Statement s = con.createStatement();
            PreparedStatement st;
            String sql;
            if(p.length()<8){
                JOptionPane.showMessageDialog(this, "PASSWORD must have atleast 8 characters","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(a>0&&a<150){
                if(ql.equals("")){
                    sql = "Insert into perauth(fname,lname,age,gender,uname,upass)values('"+(r)+"','"+(n)+"',"+(a)+",'"+(g)+"','"+(u)+"','"+(p)+"')";
                }
                else{
                    sql = "Insert into perauth values('"+(r)+"','"+(n)+"',"+(a)+",'"+(g)+"','"+(u)+"','"+(p)+"','"+(ql)+"')";
                }
                s.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Your Account Has Been Created.");
            t5.setText("");
            t6.setText("");
            t4.setText("");
            t3.setText("");
            t2.setText("");
            t1.setText("");
            t7.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid Age","Error",JOptionPane.ERROR_MESSAGE);
            }
            s.close();
            con.close();
        }
        catch(Exception e){
            int count = 0,ch=0;
            Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, e);
            if(t4.getText().equals("Gender")){
                count++;
                ch=1;  
            }
            if(t1.getText().equals("Firstname")){
                ch=2;
                count++; 
            }
            if(t2.getText().equals("Lastname")){
                count++;
                ch=3;
            }
            if(t6.getText().equals("Username")){
                count++;
                ch=4;  
            }
            if(t7.getText().equals("Password")){
                count++;
                ch=5;
            }
            if(t3.getText().equals("Age")){
                count++;
                ch=6;
            }
            if(count==1){
                switch (ch){
                case 1:
                    JOptionPane.showMessageDialog(this, "GENDER Cannot Be Empty","Error",JOptionPane.ERROR_MESSAGE);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(this, "FIRST NAME Cannot Be Empty","Error",JOptionPane.ERROR_MESSAGE);
                    break;
                case 3:
                    JOptionPane.showMessageDialog(this, "LAST NAME Cannot Be Empty","Error",JOptionPane.ERROR_MESSAGE);
                    break;
                case 4:
                    JOptionPane.showMessageDialog(this, "USERNAME Cannot Be Empty","Error",JOptionPane.ERROR_MESSAGE);
                    break;
                case 5:
                    JOptionPane.showMessageDialog(this, "Password Cannot Be Empty","Error",JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Age Cannot Be Empty","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Multiple Mandatory Fields Empty(Excluding Qualification)","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel10Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10Exit
        System.exit(0);
    }//GEN-LAST:event_jLabel10Exit

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l1MouseClicked

    private void jFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-posX, y-posY);
    }//GEN-LAST:event_jFrameMouseDragged

    private void jFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFrameMousePressed
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_jFrameMousePressed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        t1.setText("");
        if(t2.getText().equals("")){
            this.t2.setForeground(Color.LIGHT_GRAY);
            t2.setText("Lastname");
        }
        if(t3.getText().equals("")){
            this.t3.setForeground(Color.LIGHT_GRAY);
            t3.setText("Age");
        }
        if(t4.getText().equals("")){
            this.t4.setForeground(Color.LIGHT_GRAY);
            t4.setText("Gender");
        }
        if(t5.getText().equals("")){
            this.t5.setForeground(Color.LIGHT_GRAY);
            t5.setText("Qualification");
        }
        if(t6.getText().equals("")){
            this.t6.setForeground(Color.LIGHT_GRAY);
            t6.setText("Username");
        }
        if(t7.getText().equals("")){
            this.t7.setForeground(Color.LIGHT_GRAY);
            t7.setText("Password");
        }
    }//GEN-LAST:event_t1MouseClicked

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        t2.setText("");
        if(t1.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t1.setText("Firstname");
        }
        if(t3.getText().equals("")){
            this.t3.setForeground(Color.LIGHT_GRAY);
            t3.setText("Age");
        }
        if(t4.getText().equals("")){
            this.t4.setForeground(Color.LIGHT_GRAY);
            t4.setText("Gender");
        }
        if(t5.getText().equals("")){
            this.t5.setForeground(Color.LIGHT_GRAY);
            t5.setText("Qualification");
        }
        if(t6.getText().equals("")){
            this.t6.setForeground(Color.LIGHT_GRAY);
            t6.setText("Username");
        }
        if(t7.getText().equals("")){
            this.t7.setForeground(Color.LIGHT_GRAY);
            t7.setText("Password");
        }
    }//GEN-LAST:event_t2MouseClicked

    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
        t3.setText("");
        if(t1.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t1.setText("Firstname");
        }
        if(t2.getText().equals("")){
            this.t2.setForeground(Color.LIGHT_GRAY);
            t2.setText("Lastname");
        }
        if(t4.getText().equals("")){
            this.t4.setForeground(Color.LIGHT_GRAY);
            t4.setText("Gender");
        }
        if(t5.getText().equals("")){
            this.t5.setForeground(Color.LIGHT_GRAY);
            t5.setText("Qualification");
        }
        if(t6.getText().equals("")){
            this.t6.setForeground(Color.LIGHT_GRAY);
            t6.setText("Username");
        }
        if(t7.getText().equals("")){
            this.t7.setForeground(Color.LIGHT_GRAY);
            t7.setText("Password");
        }
    }//GEN-LAST:event_t3MouseClicked

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        t4.setText("");
        if(t1.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t1.setText("Firstname");
        }
        if(t2.getText().equals("")){
            this.t2.setForeground(Color.LIGHT_GRAY);
            t2.setText("Lastname");
        }
        if(t3.getText().equals("")){
            this.t3.setForeground(Color.LIGHT_GRAY);
            t3.setText("Age");
        }
        if(t5.getText().equals("")){
            this.t5.setForeground(Color.LIGHT_GRAY);
            t5.setText("Qualification");
        }
        if(t6.getText().equals("")){
            this.t6.setForeground(Color.LIGHT_GRAY);
            t6.setText("Username");
        }
        if(t7.getText().equals("")){
            this.t7.setForeground(Color.LIGHT_GRAY);
            t7.setText("Password");
        }
    }//GEN-LAST:event_t4MouseClicked

    private void t5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseClicked
        t5.setText("");
        if(t1.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t1.setText("Firstname");
        }
        if(t2.getText().equals("")){
            this.t2.setForeground(Color.LIGHT_GRAY);
            t2.setText("Lastname");
        }
        if(t3.getText().equals("")){
            this.t3.setForeground(Color.LIGHT_GRAY);
            t3.setText("Age");
        }
        if(t4.getText().equals("")){
            this.t4.setForeground(Color.LIGHT_GRAY);
            t4.setText("Gender");
        }
        if(t6.getText().equals("")){
            this.t6.setForeground(Color.LIGHT_GRAY);
            t6.setText("Username");
        }
        if(t7.getText().equals("")){
            this.t7.setForeground(Color.LIGHT_GRAY);
            t7.setText("Password");
        }
    }//GEN-LAST:event_t5MouseClicked

    private void t6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t6MouseClicked
        t6.setText("");
        if(t1.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t1.setText("Firstname");
        }
        if(t2.getText().equals("")){
            this.t2.setForeground(Color.LIGHT_GRAY);
            t2.setText("Lastname");
        }
        if(t3.getText().equals("")){
            this.t3.setForeground(Color.LIGHT_GRAY);
            t3.setText("Age");
        }
        if(t4.getText().equals("")){
            this.t4.setForeground(Color.LIGHT_GRAY);
            t4.setText("Gender");
        }
        if(t5.getText().equals("")){
            this.t5.setForeground(Color.LIGHT_GRAY);
            t5.setText("Qualification");
        }
        if(t7.getText().equals("")){
            this.t7.setForeground(Color.LIGHT_GRAY);
            t7.setText("Password");
        }
    }//GEN-LAST:event_t6MouseClicked

    private void t7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t7MouseClicked
        t7.setText("");
        if(t1.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t1.setText("Firstname");
        }
        if(t2.getText().equals("")){
            this.t2.setForeground(Color.LIGHT_GRAY);
            t2.setText("Lastname");
        }
        if(t3.getText().equals("")){
            this.t3.setForeground(Color.LIGHT_GRAY);
            t3.setText("Age");
        }
        if(t4.getText().equals("")){
            this.t4.setForeground(Color.LIGHT_GRAY);
            t4.setText("Gender");
        }
        if(t5.getText().equals("")){
            this.t1.setForeground(Color.LIGHT_GRAY);
            t5.setText("Qualification");
        }
        if(t6.getText().equals("")){
            this.t6.setForeground(Color.LIGHT_GRAY);
            t6.setText("Username");
        }
    }//GEN-LAST:event_t7MouseClicked

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        this.t1.setForeground(Color.BLACK);
    }//GEN-LAST:event_t1KeyTyped

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        this.t2.setForeground(Color.BLACK);
    }//GEN-LAST:event_t2KeyTyped

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
        this.t3.setForeground(Color.BLACK);
    }//GEN-LAST:event_t3KeyTyped

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        this.t4.setForeground(Color.BLACK);
    }//GEN-LAST:event_t4KeyTyped

    private void t5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyTyped
        this.t5.setForeground(Color.BLACK);
    }//GEN-LAST:event_t5KeyTyped

    private void t6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyTyped
        this.t6.setForeground(Color.BLACK);
    }//GEN-LAST:event_t6KeyTyped

    private void t7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyTyped
        this.t7.setForeground(Color.BLACK);
    }//GEN-LAST:event_t7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
